### ISSUE TITLE
#02 Authentication Page

### ISSUE THREAD

**Issue by rohit7979** [rohit7979/Spotify-Strategists_022#2]
### Description
The section will consists of Sign-up and Login page. 
### Tasks List
- [x] Create Signup page
- [x] Create Login page
- [x] Create respective Js files 

 
### Environment
- Operating System: Windows 10, macOS
- Browser: Chrome, Brave

**Comment by rohit7979** [comment]
all task has completed
