### ISSUE TITLE
#011 Product display page

### ISSUE THREAD

**Issue by rohit7979** [rohit7979/Spotify-Strategists_022#24]
### Description
The section will consists of a Product display page. 
### Tasks List
- [x] create product display html file 
- [x] apply related css 
- [x] apply related javascript

 
### Environment
- Operating System: Windows 10, macOS
- Browser: Chrome, Brave

**Comment by RtoRakesh** [comment]
style part need to add
