### ISSUE TITLE
#012 Wish List page

### ISSUE THREAD

**Issue by rohit7979** [rohit7979/Spotify-Strategists_022#25]
### Description
The section will consists of wish list page. 
### Tasks List
- [x] create wish list html file 
- [x] apply related CSS 
- [x] apply related JavaScript

 
### Environment
- Operating System: Windows 10, macOS
- Browser: Chrome, Brave

**Comment by rohit7979** [comment]
wishlist html and js file created
