### ISSUE TITLE
#013 My Bag page

### ISSUE THREAD

**Issue by rohit7979** [rohit7979/Spotify-Strategists_022#26]
### Description
The section will consists of a My Bag page. 
### Tasks List
- [x] create My Bag html file 
- [x] apply related CSS 
- [x] apply related JavaScript

 
### Environment
- Operating System: Windows 10, macOS
- Browser: Chrome, Brave

**Comment by Rutvik020302** [comment]
Html and javaScript file created for my bag page.
